[[shards]]
name = "Delhi"
idx = 0
address = "127.0.0.2:8080"
replicas = ["127.0.0.22:8080"]

[[shards]]
name = "Mumbai"
idx = 1
address = "127.0.0.3:8080"
replicas = ["127.0.0.33:8080"]

[[shards]]
name = "Hyderabad"
idx = 2
address = "127.0.0.4:8080"
replicas = ["127.0.0.44:8080"]

[[shards]]
name = "Chennai"
idx = 3
address = "127.0.0.5:8080"
replicas = ["127.0.0.55:8080"]