[[shards]]
name = "Delhi"
idx = 0
address = "localhost:8080"

[[shards]]
name = "Mumbai"
idx = 1
address = "localhost:8081"

[[shards]]
name = "ggwp"
idx = 2
address = "localhost:8082"

[[shards]]
name = "nicetry"
idx = 3
address = "localhost:8083"